name: livewire
recipe: laravel

config:
  php: '8.1'
  composer_version: 2-latest
  via: nginx
  webroot: public
  database: mysql:5.7
  cache: redis
  xdebug: false

services:
  node:
    type: node
   
tooling:
  npm:
    service: node

